### ISSUE TITLE
Startup issues

### ISSUE THREAD

**Issue by ryzendew** [20PercentRendered/opensteamclient#48]
```System.IO.FileNotFoundException: Could not find file '/home/matt/.local/share/OpenSteam/ubuntu12_32/steam-runtime.checksum'.
File name: '/home/matt/.local/share/OpenSteam/ubuntu12_32/steam-runtime.checksum'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at OpenSteamworks.Client.Startup.Bootstrapper.CheckSteamRuntime(IExtendedProgress`1 progressHandler) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Startup/Bootstrapper.cs:line 779
   at OpenSteamworks.Client.Startup.Bootstrapper.RunBootstrap() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Startup/Bootstrapper.cs:line 274
   at OpenSteamClient.AvaloniaApp.OnFrameworkInitializationCompleted() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamClient/AvaloniaApp.axaml.cs:line 79
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OpenSteamClient.Program.Main(String[] args) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamClient/Program.cs:line 37```


Arch Linux

**Comment by Rosentti** [comment]
Please recompile and retry. I've pushed out a possible fix.

**Comment by Rosentti** [comment]
Oops, forgot to commit the other file, if you ran into a build error please retry once more.

**Comment by ryzendew** [comment]
![image](https://github.com/OpenSteamClient/OpenSteamClient/assets/84041391/5e754cbc-f028-4edd-ad80-79354a65cc6d)
new issue it doesn't see my linux 

```System.NotSupportedException: This build has not been compiled with support for linux-x64. Please rebuild or try another OS. 
Alternatively, if you're running on 64-bit Windows, 64-bit Linux or 64-bit MacOS file an issue if this is a release build.
   at OpenSteamworks.Client.Startup.Bootstrapper.CopyOpensteamFiles(IExtendedProgress`1 progressHandler) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Startup/Bootstrapper.cs:line 987
   at OpenSteamworks.Client.Startup.Bootstrapper.RunBootstrap(Action`2 msgBoxProvider) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Startup/Bootstrapper.cs:line 360
   at OpenSteamClient.AvaloniaApp.OnFrameworkInitializationCompleted() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamClient/AvaloniaApp.axaml.cs:line 79
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OpenSteamClient.Program.Main(String[] args) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamClient/Program.cs:line 37```

**Comment by Rosentti** [comment]
I've pushed an update, please retry.

**Comment by ryzendew** [comment]
![image](https://github.com/OpenSteamClient/OpenSteamClient/assets/84041391/ab4fc0c9-81a6-4339-ada2-64a2069cc0cd)

```
OpenSteamClient has encountered a fatal exception. Exception message: An error occurred trying to start process '/home/matt/.local/share/OpenSteam/steamserviced' with working directory '/home/matt/.local/share/OpenSteam'. No such file or directory
```

```System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/home/matt/.local/share/OpenSteam/steamserviced' with working directory '/home/matt/.local/share/OpenSteam'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at OpenSteamworks.Client.Startup.SteamService.StartServiceAsHost(String pathToHost) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Startup/SteamService.cs:line 62
   at OpenSteamworks.Client.Startup.SteamService.RunStartup() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Startup/SteamService.cs:line 110
   at OpenSteamworks.Client.Utils.DI.Container.RunClientStartup() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Utils/DI/Container.cs:line 383
   at OpenSteamClient.AvaloniaApp.OnFrameworkInitializationCompleted() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamClient/AvaloniaApp.axaml.cs:line 86
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OpenSteamClient.Program.Main(String[] args) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamClient/Program.cs:line 37```

**Comment by ryzendew** [comment]
i fixed that last one by placing the missing file but got this now 
![image](https://github.com/OpenSteamClient/OpenSteamClient/assets/84041391/a506d6ac-3b27-421e-bbbf-66b5112457a2)

```
OpenSteamClient has encountered a fatal exception. Exception message: One or more errors occurred. (There are less filter groups than 7. Have the filters changed? New length is: 6)
```

```System.AggregateException: One or more errors occurred. (There are less filter groups than 7. Have the filters changed? New length is: 6)
 ---> System.InvalidOperationException: There are less filter groups than 7. Have the filters changed? New length is: 6
   at OpenSteamworks.Client.Apps.Library.Collection.FromJSONCollection(JSONCollection json) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Apps/Library/Collection.cs:line 73
   at OpenSteamworks.Client.Apps.Library.Library.InitializeLibrary() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Apps/Library/Library.cs:line 78
   at OpenSteamworks.Client.Apps.Library.LibraryManager.OnLoggedOn(IExtendedProgress`1 progress, LoggedOnEventArgs e) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Apps/Library/LibraryManager.cs:line 65
   at OpenSteamworks.Client.Utils.DI.Container.RunLogon(IExtendedProgress`1 progress, LoggedOnEventArgs e) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Utils/DI/Container.cs:line 424
   at OpenSteamworks.Client.Managers.LoginManager.OnLoggedOn(LoggedOnEventArgs e) in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Login/LoginManager.cs:line 561
   at OpenSteamworks.Client.Managers.LoginManager.<>c__DisplayClass71_0.<<BeginLogonToUser>b__0>d.MoveNext() in /home/runner/work/OpenSteamClient/OpenSteamClient/OpenSteamworks.Client/Login/LoginManager.cs:line 496
   --- End of inner exception stack trace ---```

**Comment by Rosentti** [comment]
Could you send logs/Library.log? It'll contain the JSON of your collections, the collection's names and contents as well as any dynamic filters.

**Comment by ryzendew** [comment]
Issue the library log was empty

**Comment by Rosentti** [comment]
I've pushed out a temporary fix to the logging issue. Now you should be able to get the logs.

**Comment by ryzendew** [comment]
> I've pushed out a temporary fix to the logging issue. Now you should be able to get the logs.

[Library.log](https://github.com/user-attachments/files/15749028/Library.log)

that did fix the logs

**Comment by ryzendew** [comment]
![image](https://github.com/OpenSteamClient/OpenSteamClient/assets/84041391/43d470f8-ba96-481d-b4b1-55f1dc8fde6c)
your newest fix works! im in thank you so much!
