### ISSUE TITLE
Common section does not exist when family sharing

### ISSUE THREAD

**Issue by SinnerK0N** [20PercentRendered/opensteamclient#49]
I own this game [https://store.steampowered.com/app/31280/Poker_Night_at_the_Inventory/](https://store.steampowered.com/app/31280/Poker_Night_at_the_Inventory/). When I log in to the account that bought it works fine. However when I log in to an account that got the game by family sharing it crashes with this exception `Unhandled exception. System.NullReferenceException: Common section does not exist for app 31280` rendering the account unusable.

Here is the log:
```
Firing library updated
Unhandled exception. System.NullReferenceException: Common section does not exist for app 31280
at OpenSteamworks.Client.Apps.SteamApp..ctor(AppId_t appid) in /home/sinner/Downloads/opensteam/opensteamclient/OpenSteamworks.Client/Apps/SteamApp.cs:line 63
at OpenSteamworks.Client.Apps.AppBase.CreateSteamApp(AppId_t appid) in /home/sinner/Downloads/opensteam/opensteamclient/OpenSteamworks.Client/Apps/AppBase.cs:line 163
at OpenSteamworks.Client.Apps.AppsManager.GetApp(AppId_t appid) in /home/sinner/Downloads/opensteam/opensteamclient/OpenSteamworks.Client/Apps/AppsManager.cs:line 301
at OpenSteamworks.Client.Apps.AppsManager.GetApp(CGameID gameid) in /home/sinner/Downloads/opensteam/opensteamclient/OpenSteamworks.Client/Apps/AppsManager.cs:line 268
at OpenSteamworks.Client.Apps.Library.LibraryManager.<>c__DisplayClass21_0.<OnLoggedOn>b__1(CGameID appid) in /home/sinner/Downloads/opensteam/opensteamclient/OpenSteamworks.Client/Apps/Library/LibraryManager.cs:line 73
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at OpenSteamworks.Client.Apps.Library.LibraryManager.<>c__DisplayClass21_0.<<OnLoggedOn>b__0>d.MoveNext() in /home/sinner/Downloads/opensteam/opensteamclient/OpenSteamworks.Client/Apps/Library/LibraryManager.cs:line 74
--- End of stack trace from previous location ---
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by Rosentti** [comment]
That's strange, I didn't think family sharing worked yet, since I haven't written any extra code for it. 
I'll look into this.

**Comment by SinnerK0N** [comment]
I didnt family share with OpenSteamClient, I did that with normal Steam a few months ago. Sorry I should have clarified that.

**Comment by Rosentti** [comment]
It seems the problem isn't related to family sharing. You just have an unowned app (only direct apps count, family share, etc is ignored) in your collections, which we don't currently handle (fix incoming).

**Comment by Rosentti** [comment]
Fix released, please retest.

**Comment by SinnerK0N** [comment]
Works fine now, thank you!
