### ISSUE TITLE
Cannot properly open client on c#-rewrite branch

### ISSUE THREAD

**Issue by Meister1593** [20PercentRendered/opensteamclient#52]
When i open it, login and then main window opens, huge stack trace with this error appears:

```
System.AggregateException: One or more errors occurred. (Exception has been thrown by the target of an invocation.)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Common section does not exist for app 590830
   at OpenSteamworks.Client.Apps.SteamApp..ctor(AppId_t appid) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Apps/SteamApp.cs:line 64
   at OpenSteamworks.Client.Apps.AppBase.CreateSteamApp(AppId_t appid) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Apps/AppBase.cs:line 163
   at OpenSteamworks.Client.Apps.AppsManager.GetApp(AppId_t appid) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Apps/AppsManager.cs:line 290
   at OpenSteamworks.Client.Apps.AppsManager.GetApp(CGameID gameid) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Apps/AppsManager.cs:line 257
   at OpenSteamClient.ViewModels.Library.LibraryAppViewModel..ctor(CGameID gameid) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/ViewModels/Library/LibraryAppViewModel.cs:line 27
   at OpenSteamClient.ViewModels.LibraryPageViewModel.OnLibraryUpdated(Object sender, EventArgs e) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/ViewModels/LibraryPageViewModel.cs:line 84
   at OpenSteamClient.ViewModels.LibraryPageViewModel..ctor(AppsManager appsManager, LibraryManager libraryManager) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/ViewModels/LibraryPageViewModel.cs:line 55
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenSteamworks.Client.Utils.DI.Container.ConstructOnly(Type type, Object[] extraArgs) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Utils/DI/Container.cs:line 253
   at OpenSteamClient.ViewModels.PageHeaderViewModel.<>c__DisplayClass35_0.<.ctor>b__1(Object page) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/ViewModels/PageHeaderViewModel.cs:line 74
   at OpenSteamClient.ViewModels.MainWindowViewModel.SwitchToPage(Type pageType) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/ViewModels/MainWindowViewModel.cs:line 102
   at OpenSteamClient.ViewModels.MainWindowViewModel..ctor(MainWindow mainWindow, ISteamClient client, AppsManager appsManager, TranslationManager tm, LoginManager loginManager, Action openSettingsWindowAction) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/ViewModels/MainWindowViewModel.cs:line 88
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OpenSteamworks.Client.Utils.DI.Container.ConstructOnly[T](Object[] extraArgs) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Utils/DI/Container.cs:line 261
   at OpenSteamClient.AvaloniaApp.ForceMainWindow() in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/AvaloniaApp.axaml.cs:line 196
   at OpenSteamClient.AvaloniaApp.<>c__DisplayClass11_0.<OnFrameworkInitializationCompleted>b__8() in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/AvaloniaApp.axaml.cs:line 98
   at Avalonia.Threading.DispatcherOperation.InvokeCore()
--- End of stack trace from previous location ---
   at Avalonia.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at Avalonia.Threading.DispatcherOperation.Wait()
   at Avalonia.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at Avalonia.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at Avalonia.Threading.Dispatcher.Invoke(Action callback)
   at OpenSteamClient.AvaloniaApp.InvokeOnUIThread(Action callback) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/AvaloniaApp.axaml.cs:line 62
   at OpenSteamClient.AvaloniaApp.<>c__DisplayClass11_0.<OnFrameworkInitializationCompleted>b__1(Object sender, LoggedOnEventArgs e) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamClient/AvaloniaApp.axaml.cs:line 95
   at OpenSteamworks.Client.Managers.LoginManager.<>c__DisplayClass79_0.<RunLogon>b__0() in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Login/LoginManager.cs:line 583
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at OpenSteamworks.Client.Managers.LoginManager.RunLogon(LoggedOnEventArgs e) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Login/LoginManager.cs:line 583
   at OpenSteamworks.Client.Managers.LoginManager.OnLoggedOn(LoggedOnEventArgs e) in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Login/LoginManager.cs:line 574
   at OpenSteamworks.Client.Managers.LoginManager.<>c__DisplayClass74_0.<<BeginLogonToUser>b__0>d.MoveNext() in /home/plyshka/Documents/Code/C#/opensteamclient/OpenSteamworks.Client/Login/LoginManager.cs:line 513
   --- End of inner exception stack trace ---
   ```

If i run it with this patch, client opens and seems to run (though proton games do not seem to start, but it might be another error, native games start)
[fix-patch.txt](https://github.com/user-attachments/files/16404194/fix-patch.txt)

**Comment by Meister1593** [comment]
Correction: Most proton games did not launch (`7 days to die` without EAC doesnt work, `rain world` doesnt work,  `factorio` native did not work, `Deep rock galactic` works)

**Comment by Rosentti** [comment]
Peculiar. There's some problems with the appinfo not existing even when it should but this is usually fixed by starting OpenSteamClient a couple times. After that it shouldn't really a problem. 

The patch doesn't solve the underlying problem (appinfo missing), and instead masks it by simply initializing the appinfo to null values, which will cause game launching problems, cloud sync problems, problems where the apps aren't visible in the library and possibly further exceptions, since the common section provides us the app's name, corrected gameid, icons, proton data and more. 

I'd advise to unpatch and relaunch and login a bunch of times, try 5 or so times and if it isn't solved even after that you could try another account? Other than that I can't really help too much at the moment. You could also try copying over appinfo.vdf from the official client install.

The appinfo has been very difficult to get working properly so issues like this pop up every now and then, but I have a rewrite in the works that should squash a lot of the bugs, instabilities and badly written code the client has at the moment. 

However the launching issue likely is not to do with the appinfo issue. Factorio not working is even more peculiar, as it's a native linux game. I'll look into it, but in the meanwhile proton games should become workable if you manually enable compat for them with the Interface Debugger.

**Comment by Meister1593** [comment]
I already tried launching 5 or more times, issue doesnt seem to be fixing by itself
Don't have another account... might try to check with another blank account
> You could also try copying over appinfo.vdf from ...

from where (or rather, to where?)? this seems incomplete

**Comment by Rosentti** [comment]
Ah, lots of time has passed. Try again now? Just did some updates.
